### ISSUE TITLE
Autocomplete not working for some Entity objects

### ISSUE THREAD

**Issue by jimafisk** [fenetikm/autoload-drupal#2]
Thanks for writing this plugin, it works great!

Autocomplete is working for most of my classes, but I'm having trouble in certain cases. For example if typing `Drupal\taxonomy\Entity\Vocabulary->` it does not autocomplete. However if I edit docroot/core/modules/taxonomy/src/Entity/Vocabulary.php and remove the `extends ConfigEntityBundleBase` from the class, the autocomplete for `Vocabulary` starts working. Is this because `Drupal\Core\Config\Entity\ConfigEntityBundleBase` is not being recognized by composer's autoloader?

I tried manually adding the following to `vendor/composer/autoload_psr4.php`:
```
'Drupal\\Core\\Config\\Entity\\' => array($baseDir . '/docroot/core/lib/Drupal/Core/Config/Entity'),
```
but that didn't seem to work. Do you have thoughts on what I might be doing wrong? Thank you!

Here's my `composer.json` config in case that helps:
```
"autoload-drupal": {
  "modules": [
    "docroot/modules/contrib/",
    "docroot/core/modules/",
    "docroot/modules/custom/"
  ],
```

**Comment by jimafisk** [comment]
I followed the chain down a little, turns out `ConfigEntityBundleBase` is extending `ConfigEntityBase` which seemed fine since they were in the same namespace, but `ConfigEntityBase` uses `Drupal\Core\Entity\Entity` which was not autoloaded. Added that in `autoload_psr4.php`:
```
'Drupal\\Core\\Entity\\' => array($baseDir . '/docroot/core/lib/Drupal/Core/Entity'),
```
And entity uses a bunch of stuff not autoloaded that I added to `autoload_psr4.php` manually:
```
'Drupal\\Core\\Cache\\' => array($baseDir . '/docroot/core/lib/Drupal/Core/Cache'),
'Drupal\\Core\\DependencyInjection\\' => array($baseDir . '/docroot/core/lib/Drupal/Core/DependencyInjection'),
'Drupal\\Core\\Language\\' => array($baseDir . '/docroot/core/lib/Drupal/Core/Language'),
'Drupal\\Core\\Session\\' => array($baseDir . '/docroot/core/lib/Drupal/Core/Session'),
```

The last line that's still giving me trouble is 26: `__sleep as traitSleep;`. It [looks like](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Entity%21Entity.php/class/Entity/8.6.x) `DependencySerializationTrait::__sleep` is aliased as `traitSleep`. When I comment this line out, `Drupal\taxonomy\Entity\Vocabulary->` autocompletion works.

Any idea what's going on with `traitSleep`? Also, how should I go about adding these `autoload_psr4.php` manual entries to `composer.json`, can I use "classmap" for that? Thank you!

**Comment by jimafisk** [comment]
After trying this again, it looks like manually adding classes to `autoload_psr4.php` isn't necessary in my case. The real issue for `Drupal\taxonomy\Entity\Vocabulary->` autocomplete is line 26 in docroot/core/lib/Drupal/Core/Entity/Entity.php: `__sleep as traitSleep;`

Similarly for `Drupal\taxonomy\Entity\Term->` it works if you do the following:
1. In docroot/core/lib/Drupal/Core/Entity/ContentEntityBase.php, comment out Line 23: 
```
getFieldsToSkipFromTranslationChangesCheck as traitGetFieldsToSkipFromTranslationChangesCheck;
```
2. In docroot/core/lib/Drupal/Core/Entity/ContentEntityBase.php remove `\IteratorAggregate,` from the extends on Line 20
3. In docroot/core/lib/Drupal/Core/Entity/ContentEntityInterface.php, remove `\Traversable,` from the extends on Line 24

So it seems like this is not an issue with your plugin adding to the autoloader, but instead with phpactor itself. The first issue potentially has something to do with [working with traits](https://github.com/phpactor/phpactor/issues/320). The second issue might be because `\IteratorAggregate` is a [predefined PHP interface](https://www.php.net/manual/en/class.iteratoraggregate.php) and [I've had trouble with standard PHP](https://github.com/phpactor/ncm2-phpactor/issues/21) in the past.

**Comment by jimafisk** [comment]
Turns out I just needed to clear my phpactor cache since it was still looking for php stubs in vim after I switched to neovim: `~/.config/nvim/plugged/phpactor/bin/phpactor cache:clear`

**Comment by fenetikm** [comment]
Nice one @jimafisk - glad to hear someone is giving this plugin a go. 👍

**Comment by jimafisk** [comment]
Your plugin works really well, I think if more people knew how to set this up they'd be happy with the result. I've started the conversation here: https://www.drupal.org/project/vimrc/issues/3046876

**Comment by fenetikm** [comment]
@jimafisk nice - I haven't been doing much Drupal stuff recently, changed jobs but it would be great to get a more modern Vim setup available.
