### ISSUE TITLE
How to load .module files?

### ISSUE THREAD

**Issue by hkirsman** [fenetikm/autoload-drupal#6]
I don't think .module files are loaded as one of my module has

    define('ADOBE_CAPTIVATE_ZIP_UPLOAD_SUBFOLDER', '__uploaded__');

And in another, that constant is used. Psalm says undefined constant.

I understand .module files don't have namespace so these are not loaded, right?

**Comment by fenetikm** [comment]
yep, that's correct, they're not loaded.
