### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by DieterHolvoet** [fenetikm/autoload-drupal#8]
Composer 2 compatibility was merged in december 2020, but no tagged release has been made yet, forcing people to require `dev-master`. Let me know if any work needs to be done before creating a new release, I'd be happy to help.

**Comment by achton** [comment]
@fenetikm Any chance of a release?

**Comment by fenetikm** [comment]
Sure, why not. Hang on a tic.

**Comment by fenetikm** [comment]
There you go, pushed a `1.0.0` tag. I think that's all that is required? Cheers.

**Comment by achton** [comment]
Thanks a lot :) I do think a little more is required for it to appear on [Packagist](https://packagist.org/packages/fenetikm/autoload-drupal) though. It says that the package is not auto-updated, so I guess it needs to be manually updated. 

You can setup a [webhook](https://packagist.org/about#how-to-update-packages) I believe to get this automated.

**Comment by fenetikm** [comment]
Have updated it on packagist... maybe I'll setup a webhook next year ;)

**Comment by achton** [comment]
W00t :-) Looking forward to it 😉
